[package]
name = "vulkan-tutorial-rs"
version = "0.1.0"
authors = ["Elanis <elanis@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.11.1"
winit = "0.18.0"